GET http://localhost:8000/api/blog/ HTTP/1.1

###
GET http://localhost:8000/api/blog/featured HTTP/1.1


###
GET http://localhost:8000/api/blog/my-first-blog-post-1 HTTP/1.1

###
POST http://localhost:8000/api/blog/category HTTP/1.1
Content-Type: application/json

{
  "category": "business"
}